server:
  port: 80
spring:
  application:
    name: cloud-consumer-openfeign-order80
  datasource:
    url: jdbc:mysql://localhost:3306/clouddata?useSSL=false
    username: root
    password: zxy902
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: claaspth:com.atguigu.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka

ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    com.atguigu.springcloud.feignservice.FeignService: debug
  #以什么样的级别监控哪个接口