server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: cloud-center-config
  rabbitmq:
    host: hadoop100
    virtual-host: /
    username: admin
    password: zxy902

  datasource:
    url: jdbc:mysql://localhost:3306/clouddata?useSSL=false
    username: root
    password: zxy902
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  cloud:
    config:
      server:
        git:
          uri: https://github.com/RinneOharaX/springcloud-config.git
          search-paths:
            - springcloud-config
          force-pull: true
      label: master


  management:
    endpoints:
      web:
        exposure:
          include: 'bus-refresh'