server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  datasource:
    url: jdbc:mysql://localhost:3306/clouddata?useSSL=false
    username: root
    password: zxy902
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true
  circuitbreaker:
    enabled: true