server:
  port: 9527
spring:
  application:
    name: GateWay9527
  datasource:
      url: jdbc:mysql://localhost:3306/clouddata?useSSL=false
      username: root
      password: zxy902
      driver-class-name: org.gjt.mm.mysql.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
            - Before=2023-03-20T22:25:00.629+08:00[Asia/Shanghai]
        - id: payment_route2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            Path=/payment/creat #断言,路径相匹配的进行路由

eureka:
  instance:
    prefer-ip-address: true
    hostname: GateWay9527
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka


