server:
  port: 80
spring:
  application:
    name: cloud-consumer-zookeeper-order
  cloud:
    zookeeper:
      connect-string: hadoop100:2181

  datasource:
    url: jdbc:mysql://localhost:3306/clouddata?useSSL=false
    username: root
    password: zxy902
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: claaspth:com.atguigu.springcloud.entities